# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e2dfbe4ddb968ff4ec51dfa247bc1ab90babd4812ee0cfe87e332233fbdfd7ee21851cf88fdb922a567084422f39bd47af9f13bbb888fe5777d77f3d0374add

test:
  secret_key_base: cd87643c1ddc41a775a74988c530dea9ce61ef3121917fe87fba5cf44e1b8ef7b9369e1ab9cb45a629597dbc19fd9eff5b604fe935836a276e2578ffc00d6746

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
